var config = {
    style:  'mapbox://styles/xuanwu07/clpjfq3oz00dz01p72vdjfmap',
    accessToken: 'pk.eyJ1IjoieHVhbnd1MDciLCJhIjoiY2xuMXdhN29kMDJqeTJqbDl2ZWMxdHB0ciJ9.OB0_cwfVLHeaeHjL43cY_g',
    //projection: 'equirectangular',
    //Read more about available projections here
    //https://docs.mapbox.com/mapbox-gl-js/example/projections/
    inset: true,
    theme: 'light',
    use3dTerrain: true, //set true for enabling 3D maps.
    title: 'From Ashes to Architectural Triumph:Great Chicago Fire and Great Rebuilding',
    subtitle: 'Revisiting the great historic accident and its impact',
    byline: 'By Xuan Wu',
    para1: ' The Great Chicago Fire was a conflagration that burned in Chicago during October 8–10, 1871, one of the worst urban fires in the history of the world. For both the city and the residents, the fire was a terrible disaster, bringing huge economic loss and homeless. The fire kept burning over 24 hours in the downtown of Chicago, almost destroying all buildings in downtown. Finally, it was a  pouring rain that saved Chicago from the fire. ',
    para2: 'After the fire, Chicago started rebuilding instantly, making the city reborn and even more prosperous.  From the present perspective, the Great Chicago Fire is not all bad but provided opportunities for urban development. As author and Chicago historian Neal Samors said, “‘had the fire not occurred, ’Chicago would probably have been a much smaller metropolis and not the second largest city in the United States.”',
    footer: 'Source: The University of Chicago Library <br> Created using <a href="https://github.com/mapbox/storytelling" target="_blank">Mapbox Storytelling</a> template.',
    chapters: [
        {
            id: 'first-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Burnt Area',
            image: 'images/fire_damage.png',
            description: 'The Great Chicago Fire, the most famous in American history, claimed about 300 lives, destroyed some 17,450 buildings covering almost 3.5 square miles (9 square km), and caused $200 million in damage. Roughly one-third of the city lay in ruins, and an nearly 100,000 people was homeless.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},

            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},


            ],
        },

        {
            id: 'second-chapter',
            alignment: 'right',
            hidden: false,
            title: 'Pre Fire: Night October 7',
            description: 'The Saturday Night Fire of October 7 was an omen of the Great Chicago Fire. It happened in the southwest neighborhood, known as “Red Flash" because of the combustibility of the local buildings and their contents.  The Saturday Night Fire left Chicago’s already undermanned and underequipped firefighters critically shorthanded and overtired, and some of their equipment badly damaged.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },
        
        {
            id: 'third-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Origin ：Evening October 8',
            image: 'images/cow.jpg',
            description: 'The fire is claimed to have started at about 8:30 p.m. on October 8, in or around a small barn belonging to the O‘Leary family.  It was widely rumored that Mrs. O’Leary‘s cow kicked over a lantern and started the fire. However, the journalist who reported the story later admitted that he had made up the story and the court declared that Mrs. O’Leary was not the cause of the fire. The creation and widespread circulation of this story was related to racial discrimination against the Irish and religious strife against the Catholic Church at the time, with others transferring their anger over the fire to the pagans and the Irish .',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
                
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'forth-chapter',
            alignment: 'right',
            hidden: false,
            title: 'Cross South River: Midnight October 9',
            image: 'images/cross_river.jpg',
            description: ' Firefighters had hoped that the South Branch of the Chicago River and an area that had previously thoroughly burned would act as a natural firebreak.All along the river, however, were lumber yards, warehouses, and coal yards, and barges and numerous bridges across the river. As the fire grew, the southwest wind intensified and became superheated, causing structures to catch fire from the heat and from burning debris blown by the wind. Around midnight, flaming debris blew across the river and landed on roofs and the South Side Gas Works.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
                
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'fifth-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Expand : Morning October 9',
            image: 'images/fire_whirl.jpg',
            description: 'A major contributing factor to the fire’s spread was a meteorological phenomenon known as a fire whirl.As overheated air rises, it comes into contact with cooler air and begins to spin, creating a tornado-like effect. These fire whirls are likely what drove flaming debris so high and so far. Such debris was blown across the main branch of the Chicago River to a railroad car carrying kerosene.The fire had jumped the river a second time and was now raging across the city‘s north side.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
                
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },
        
        {
            id: 'sixth-chapter',
            alignment: 'right',
            hidden: false,
            title: 'Go North: Afternoon October 9',
            description: 'A short time after the fire jumped the river, a burning piece of timber lodged on the roof of the city’s waterworks. Within minutes, the interior of the building was engulfed in flames and the building was destroyed. With it, the city‘s water mains went dry and the city was helpless.The fire had spread to the sparsely populated areas of the north side, having thoroughly consumed the densely populated areas.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
                
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0.6,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0.6,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'seven-chapter',
            alignment: 'left',
            hidden: false,
            title: 'End : Morning October 10',
            image: 'images/end.jpg',
            description: 'Only rainfall, the lake, and stretches of unbuilt lots on the North Side finally halted the wave of destruction on the morning of October 10.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
                
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0.6,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0.6,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0.6,},
                {layer: '1burning',opacity: 0.6,},
                {layer: '2burning',opacity: 0.6,},
                {layer: '3burning',opacity: 0.6,},
                {layer: '4burning',opacity: 0.6,},
                {layer: '5burning',opacity: 0.6,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'eight-chapter',
            alignment: 'center',
            hidden: false,
            description: 'The Great Chicago Fire almost destroyed all buildings in the downtown of Chicago,  but a few have survived and even remain now as important historic preservation sites that hold the city’s spirits and memories.',
            location: {
                center: [-87.63196, 41.88216],
                zoom: 13.69,
                pitch: 45.50,
                bearing: 32.00
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},


            ],
        },

        {
            id: 'nine-chapter',
            alignment: 'right',
            title:'O‘Leary Home',
            image:'images/Oleary2.png',
            hidden: false,
            description: 'Interestingly, even though O‘Leary’s home was the origin of the entire fire, it miraculously survived and was demolished in 1880. Today it is The Chicago Fire Academy, built in 1961, still training firefighters for the city of Chicago and serving as a constant reminder to city residents of the importance of fire prevention.',
            location: {
                center: [-87.641, 41.869],
                zoom: 19.22,
                pitch: 45.00,
                bearing: 22.40
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'ten-chapter',
            alignment: 'left',
            title:'Lind Block',
            image:'images/lindblock.png',
            hidden: false,
            description: 'The Lind Block was the only completed and occupied building in the business district of the South Division that did not burn down.  This was at least partly attributable to its somewhat isolated position on the northwest corner, next to the South Branch of the Chicago River.  Here it stands unscathed amid the fire-leveled landscape all around. By dint of passing through the fire unharmed, the Lind Block could claim for over ninety years  that it was by at least two decades the oldest building in Chicago’s downtown. ',
            location: {
                center: [-87.638, 41.886],
                zoom: 16.72,
                pitch: 39.76,
                bearing: 22.40
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'eleven-chapter',
            alignment: 'right',
            title:'Water Tower',
            image:'images/watertower.png',
            hidden: false,
            description: 'The tower gained prominence after the Fire . The tower was the only public building in the burned zone to survive, and is one of just a few of the surviving structures still standing. Ironically, the pumping station stopped working during the fire. The roof, not made of limestone, caught fire and the pumps stopped working, stopped supplying water to fight the fire.  During the blaze, the roof caught fire and collapsed into the pumps, destroying them, along with any hope that there would be enough water to stop the spread of the fire. But the structure itself survived.In the years since the fire, the tower has become a symbol of old Chicago and of the city’s recovery from the fire. ',
            location: {
                center: [-87.624, 41.897],
                zoom: 17.87,
                pitch: 39.76,
                bearing: 22.40
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },
        {
            id: 'twelve-chapter',
            alignment: 'left',
            title:'St. Michael‘s Church',
            image:'images/michael.png',
            hidden: false,
            description: 'While most of Old Chicago’s infrastructure was made of wood, the church was made of brick which helped it survive the fire.Portions of the building survived—the stone walls of St. Michael’s being the only structures standing in the Old Town area. The church was quickly rebuilt.',
            location: {
                center: [-87.636, 41.913],
                zoom: 17.32,
                pitch: 39.76,
                bearing: 22.40
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '13-chapter',
            alignment: 'right',
            title:'Bellinger House',
            image:'images/bellinger2.png',
            hidden: false,
            description: 'This is the home that Chicago policeman Richard Bellinger saved from destruction while virtually all other North Division buildings in the in the path of the fire area were burned down. According to the popular story, Officer Bellinger first used water to wet down the house, and, when that ran out, turned to his store of cider. Assisted by his brother-in-law, Bellinger also cleared the dry leaves that were on the property, tore up the nearby wooden sidewalk and fence, and snuffed what sparks he could as soon as they landed.',
            location: {
                center: [-87.639, 41.922],
                zoom: 16.62,
                pitch: 51.52,
                bearing: -42.95
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '14-chapter',
            alignment: 'center',
            hidden: false,
            description: 'However，The Great Chicago Fire created a blank slate upon which Chicago was quickly rebuilt. That blank slate allowed it to become a dynamic city of innovative architecture with a fresh skyline dotted with a brand-new building called the skyscraper.it almost instantly rebuilt itself bigger and better from the ashes.The great legend of Chicago is that it‘s a ‘phoenix city’.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
        },

        {
            id: '15-chapter',
            alignment: 'center',
            image:'images/buildingnumber.png',
            hidden: false,
            description: 'The number of buildings constructed in the 1880s was much higher than in other eras, suggesting that in the two decades following the fire, Chicago embarked on a robust and dynamic phase of urban renewal. The aftermath of the Great Fire that had swept through Chicago acted as a catalyst for a comprehensive revitalization effort.',
            location: {
                center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0,
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
        },

        {
            id: '16-chapter',
            hidden: true,
            location: {
              center: [-87.63225, 41.89439],
              zoom: 13.39,
              pitch: 0.00,
              bearing: -89.60
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '17-chapter',
            hidden: true,
            location: {
              center: [-87.63225, 41.89439],
              zoom: 13.39,
              pitch: 0.00,
              bearing: -89.60
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '18-chapter',
            hidden: true,
            location: {
                center: [-87.63225, 41.89439],
                zoom: 13.39,
                pitch: 0.00,
                bearing: -89.60
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '19-chapter',
            hidden: true,
            location: {
                center: [-87.63225, 41.89439],
                zoom: 13.39,
                pitch: 0.00,
                bearing: -89.60
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '20-chapter',
            hidden: true,
            location: {
                center: [-87.63225, 41.89439],
                zoom: 13.39,
                pitch: 0.00,
                bearing: -89.60
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 1,},
                {layer: '1880',opacity: 1,},
                {layer: '1890',opacity: 1,},
                {layer: '1900',opacity: 1,},
                {layer: '1910',opacity: 1,},
            ],
        },

        {
            id: '21-chapter',
            alignment: 'left',
            image:'images/industry.png',
            hidden: false,
            title: 'Reasons for Rebuilding Success: Industrial Area',
            description: 'While the fire had devastated the downtown and North Side of Chicago, the stockyards and lumberyards on the South and West sides remained intact.Booming industries such as the Union Stockyards and lumberyards were located outside of the burn zone. The industrial boom provided a great deal of material and financial support for the Great Rebuilding. ',
            location: {
                center: [-87.66312, 41.85431],
                zoom: 12.20,
                pitch: 39.00,
                bearing: 36.45
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: 'chapter22',
            alignment: 'right',
            hidden: false,
            title: 'Reasons for Rebuilding Success: Railroad',
            description: 'Chicago’s railroad system was well developed for that time and was virtually undamaged by the fire. The dense railroad network allowed for a steady flow of relief supplies from all over the country and the world into Chicago, facilitating the rebuilding process.',
            location: {
                center: [-87.634, 41.882],
                zoom: 14.77,
                pitch: 39.00,
                bearing: 36.45
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 1,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 0,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 0,},
                {layer: 'allrailroad',opacity: 1,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '23-chapter',
            alignment: 'right',
            image:'images/allpalmer.png',
            hidden: false,
            title: 'Reconstruction Examples : Palmer House',
            description: 'Palmer House used  fireproof terra cotta tile for  roofing materials.The building itself was made of iron and brick. Palmer House, which is now part of the Hilton hotel chain, advertised itself as “The World’s Only Fire Proof Hotel.”',
            location: {
                center: [-87.625, 41.880],
                zoom: 16.74,
                pitch: 60.74,
                bearing: -44.80
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },

        {
            id: '24-chapter',
            alignment: 'left',
            image:'images/las.png',
            hidden: false,
            title: 'Reconstruction Examples : Jenney‘s Home Insurance Building',
            description: 'Jenney’ s Home Insurance Building, on LaSalle Street, was the first to make use of a steel cage to provide a building‘ s support. The steel frame allowed more large windows to be constructed on every side of the building. Natural light flooded the tall structure. The partitions between offices were made of brick and terra cotta. Built in 1884, the Home Insurance Building is considered to be the world；s first skyscraper.”',
            location: {
                center: [-87.634, 41.884],
                zoom: 16.82,
                pitch: 48.70,
                bearing: -44.55
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                { layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'burningborder',opacity: 1,},
                {layer: '0burning',opacity: 0,},
                {layer: '1burning',opacity: 0,},
                {layer: '2burning',opacity: 0,},
                {layer: '3burning',opacity: 0,},
                {layer: '4burning',opacity: 0,},
                {layer: '5burning',opacity: 0,},
                {layer: 'allpoint',opacity: 1,},
                {layer: 'allrailroad',opacity: 0,},
                {layer: '1870',opacity: 0,},
                {layer: '1880',opacity: 0,},
                {layer: '1890',opacity: 0,},
                {layer: '1900',opacity: 0,},
                {layer: '1910',opacity: 0,},
            ],
        },



        {
            id: 'interlude',
            alignment: 'center',
            hidden: false,
            
            description: 'The greatest impact on Chicago and other cities from the Great Chicago Fire is the formation of the Chicago School and the spring-up of skyscrapers. The rebuilding attracted a lot of architects to search for jobs in Chicago where they explored new materials and new construction skills.Chicago’s architects worked to meet the demands of commercial businessmen. Businessmen preferred plain-looking buildings, because putting on fancy ornaments cost more money. This streamlined style became known as the Chicago School of architecture.',
            
            location: {
              center: [-87.62803, 41.89321],
                zoom: 12.5,
                pitch: 0,
                bearing: 0
            },
        },
        
    ]
};
